/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChartPattern {
  'direction' : ChartPatternDirection,
  'accuracyPercentage' : bigint,
  'timeframe' : string,
  'patternName' : string,
  'description' : string,
  'detectionTimestamp' : Time,
  'tradingPair' : string,
}
export type ChartPatternDirection = { 'bullish' : null } |
  { 'bearish' : null };
export interface LiquiditySweep {
  'priceLevel' : number,
  'volume' : number,
  'timestamp' : Time,
  'sweepType' : LiquiditySweepType,
  'tradingPair' : string,
}
export type LiquiditySweepType = { 'bsl' : null } |
  { 'ssl' : null };
export interface MarketSentiment {
  'asset' : string,
  'bearishPercentage' : bigint,
  'bullishPercentage' : bigint,
  'timestamp' : Time,
}
export interface SmcZone {
  'priceLevel' : number,
  'timeframe' : string,
  'strength' : bigint,
  'zoneType' : SmcZoneType,
  'timestamp' : Time,
  'tradingPair' : string,
}
export type SmcZoneType = { 'bos' : null } |
  { 'choch' : null } |
  { 'fairValueGap' : null } |
  { 'orderBlock' : null };
export type Time = bigint;
export interface TradingSignal {
  'status' : TradingSignalStatus,
  'takeProfit' : number,
  'stopLoss' : number,
  'timestamp' : Time,
  'entryPrice' : number,
  'accuracyScore' : bigint,
  'tradingPair' : string,
  'strategyName' : string,
  'signalType' : TradingSignalType,
}
export type TradingSignalStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'pending' : null };
export type TradingSignalType = { 'buy' : null } |
  { 'sell' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChartPattern' : ActorMethod<[ChartPattern], bigint>,
  'addLiquiditySweep' : ActorMethod<[LiquiditySweep], bigint>,
  'addSmcZone' : ActorMethod<[SmcZone], bigint>,
  'addTradingSignal' : ActorMethod<[TradingSignal], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChartPatterns' : ActorMethod<[], Array<ChartPattern>>,
  'getLiquiditySweeps' : ActorMethod<[], Array<LiquiditySweep>>,
  'getMarketSentiment' : ActorMethod<[string], [] | [MarketSentiment]>,
  'getSmcZones' : ActorMethod<[], Array<SmcZone>>,
  'getTradingSignals' : ActorMethod<[], Array<TradingSignal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMarketSentiment' : ActorMethod<[MarketSentiment], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];