/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChartPatternDirection = IDL.Variant({
  'bullish' : IDL.Null,
  'bearish' : IDL.Null,
});
export const Time = IDL.Int;
export const ChartPattern = IDL.Record({
  'direction' : ChartPatternDirection,
  'accuracyPercentage' : IDL.Nat,
  'timeframe' : IDL.Text,
  'patternName' : IDL.Text,
  'description' : IDL.Text,
  'detectionTimestamp' : Time,
  'tradingPair' : IDL.Text,
});
export const LiquiditySweepType = IDL.Variant({
  'bsl' : IDL.Null,
  'ssl' : IDL.Null,
});
export const LiquiditySweep = IDL.Record({
  'priceLevel' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : Time,
  'sweepType' : LiquiditySweepType,
  'tradingPair' : IDL.Text,
});
export const SmcZoneType = IDL.Variant({
  'bos' : IDL.Null,
  'choch' : IDL.Null,
  'fairValueGap' : IDL.Null,
  'orderBlock' : IDL.Null,
});
export const SmcZone = IDL.Record({
  'priceLevel' : IDL.Float64,
  'timeframe' : IDL.Text,
  'strength' : IDL.Nat,
  'zoneType' : SmcZoneType,
  'timestamp' : Time,
  'tradingPair' : IDL.Text,
});
export const TradingSignalStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const TradingSignalType = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const TradingSignal = IDL.Record({
  'status' : TradingSignalStatus,
  'takeProfit' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'timestamp' : Time,
  'entryPrice' : IDL.Float64,
  'accuracyScore' : IDL.Nat,
  'tradingPair' : IDL.Text,
  'strategyName' : IDL.Text,
  'signalType' : TradingSignalType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MarketSentiment = IDL.Record({
  'asset' : IDL.Text,
  'bearishPercentage' : IDL.Nat,
  'bullishPercentage' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChartPattern' : IDL.Func([ChartPattern], [IDL.Nat], []),
  'addLiquiditySweep' : IDL.Func([LiquiditySweep], [IDL.Nat], []),
  'addSmcZone' : IDL.Func([SmcZone], [IDL.Nat], []),
  'addTradingSignal' : IDL.Func([TradingSignal], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChartPatterns' : IDL.Func([], [IDL.Vec(ChartPattern)], ['query']),
  'getLiquiditySweeps' : IDL.Func([], [IDL.Vec(LiquiditySweep)], ['query']),
  'getMarketSentiment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MarketSentiment)],
      ['query'],
    ),
  'getSmcZones' : IDL.Func([], [IDL.Vec(SmcZone)], ['query']),
  'getTradingSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMarketSentiment' : IDL.Func([MarketSentiment], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChartPatternDirection = IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChartPattern = IDL.Record({
    'direction' : ChartPatternDirection,
    'accuracyPercentage' : IDL.Nat,
    'timeframe' : IDL.Text,
    'patternName' : IDL.Text,
    'description' : IDL.Text,
    'detectionTimestamp' : Time,
    'tradingPair' : IDL.Text,
  });
  const LiquiditySweepType = IDL.Variant({
    'bsl' : IDL.Null,
    'ssl' : IDL.Null,
  });
  const LiquiditySweep = IDL.Record({
    'priceLevel' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : Time,
    'sweepType' : LiquiditySweepType,
    'tradingPair' : IDL.Text,
  });
  const SmcZoneType = IDL.Variant({
    'bos' : IDL.Null,
    'choch' : IDL.Null,
    'fairValueGap' : IDL.Null,
    'orderBlock' : IDL.Null,
  });
  const SmcZone = IDL.Record({
    'priceLevel' : IDL.Float64,
    'timeframe' : IDL.Text,
    'strength' : IDL.Nat,
    'zoneType' : SmcZoneType,
    'timestamp' : Time,
    'tradingPair' : IDL.Text,
  });
  const TradingSignalStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
  });
  const TradingSignalType = IDL.Variant({
    'buy' : IDL.Null,
    'sell' : IDL.Null,
  });
  const TradingSignal = IDL.Record({
    'status' : TradingSignalStatus,
    'takeProfit' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'timestamp' : Time,
    'entryPrice' : IDL.Float64,
    'accuracyScore' : IDL.Nat,
    'tradingPair' : IDL.Text,
    'strategyName' : IDL.Text,
    'signalType' : TradingSignalType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MarketSentiment = IDL.Record({
    'asset' : IDL.Text,
    'bearishPercentage' : IDL.Nat,
    'bullishPercentage' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChartPattern' : IDL.Func([ChartPattern], [IDL.Nat], []),
    'addLiquiditySweep' : IDL.Func([LiquiditySweep], [IDL.Nat], []),
    'addSmcZone' : IDL.Func([SmcZone], [IDL.Nat], []),
    'addTradingSignal' : IDL.Func([TradingSignal], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChartPatterns' : IDL.Func([], [IDL.Vec(ChartPattern)], ['query']),
    'getLiquiditySweeps' : IDL.Func([], [IDL.Vec(LiquiditySweep)], ['query']),
    'getMarketSentiment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MarketSentiment)],
        ['query'],
      ),
    'getSmcZones' : IDL.Func([], [IDL.Vec(SmcZone)], ['query']),
    'getTradingSignals' : IDL.Func([], [IDL.Vec(TradingSignal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMarketSentiment' : IDL.Func([MarketSentiment], [], []),
  });
};

export const init = ({ IDL }) => { return []; };