/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MarketSentiment {
    asset: string;
    bearishPercentage: bigint;
    bullishPercentage: bigint;
    timestamp: Time;
}
export interface ChartPattern {
    direction: ChartPatternDirection;
    accuracyPercentage: bigint;
    timeframe: string;
    patternName: string;
    description: string;
    detectionTimestamp: Time;
    tradingPair: string;
}
export type Time = bigint;
export interface SmcZone {
    priceLevel: number;
    timeframe: string;
    strength: bigint;
    zoneType: SmcZoneType;
    timestamp: Time;
    tradingPair: string;
}
export interface LiquiditySweep {
    priceLevel: number;
    volume: number;
    timestamp: Time;
    sweepType: LiquiditySweepType;
    tradingPair: string;
}
export interface UserProfile {
    name: string;
}
export interface TradingSignal {
    status: TradingSignalStatus;
    takeProfit: number;
    stopLoss: number;
    timestamp: Time;
    entryPrice: number;
    accuracyScore: bigint;
    tradingPair: string;
    strategyName: string;
    signalType: TradingSignalType;
}
export enum ChartPatternDirection {
    bullish = "bullish",
    bearish = "bearish"
}
export enum LiquiditySweepType {
    bsl = "bsl",
    ssl = "ssl"
}
export enum SmcZoneType {
    bos = "bos",
    choch = "choch",
    fairValueGap = "fairValueGap",
    orderBlock = "orderBlock"
}
export enum TradingSignalStatus {
    closed = "closed",
    active = "active",
    pending = "pending"
}
export enum TradingSignalType {
    buy = "buy",
    sell = "sell"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addChartPattern(pattern: ChartPattern): Promise<bigint>;
    addLiquiditySweep(sweep: LiquiditySweep): Promise<bigint>;
    addSmcZone(zone: SmcZone): Promise<bigint>;
    addTradingSignal(signal: TradingSignal): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChartPatterns(): Promise<Array<ChartPattern>>;
    getLiquiditySweeps(): Promise<Array<LiquiditySweep>>;
    getMarketSentiment(asset: string): Promise<MarketSentiment | null>;
    getSmcZones(): Promise<Array<SmcZone>>;
    getTradingSignals(): Promise<Array<TradingSignal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateMarketSentiment(sentiment: MarketSentiment): Promise<void>;
}
import type { ChartPattern as _ChartPattern, ChartPatternDirection as _ChartPatternDirection, LiquiditySweep as _LiquiditySweep, LiquiditySweepType as _LiquiditySweepType, MarketSentiment as _MarketSentiment, SmcZone as _SmcZone, SmcZoneType as _SmcZoneType, Time as _Time, TradingSignal as _TradingSignal, TradingSignalStatus as _TradingSignalStatus, TradingSignalType as _TradingSignalType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addChartPattern(arg0: ChartPattern): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChartPattern(to_candid_ChartPattern_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChartPattern(to_candid_ChartPattern_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLiquiditySweep(arg0: LiquiditySweep): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLiquiditySweep(to_candid_LiquiditySweep_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLiquiditySweep(to_candid_LiquiditySweep_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSmcZone(arg0: SmcZone): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSmcZone(to_candid_SmcZone_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSmcZone(to_candid_SmcZone_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTradingSignal(arg0: TradingSignal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTradingSignal(to_candid_TradingSignal_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTradingSignal(to_candid_TradingSignal_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChartPatterns(): Promise<Array<ChartPattern>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChartPatterns();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChartPatterns();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiquiditySweeps(): Promise<Array<LiquiditySweep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiquiditySweeps();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiquiditySweeps();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketSentiment(arg0: string): Promise<MarketSentiment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketSentiment(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketSentiment(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmcZones(): Promise<Array<SmcZone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmcZones();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmcZones();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradingSignals(): Promise<Array<TradingSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingSignals();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingSignals();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateMarketSentiment(arg0: MarketSentiment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketSentiment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketSentiment(arg0);
            return result;
        }
    }
}
function from_candid_ChartPatternDirection_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartPatternDirection): ChartPatternDirection {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ChartPattern_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartPattern): ChartPattern {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_LiquiditySweepType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiquiditySweepType): LiquiditySweepType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_LiquiditySweep_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LiquiditySweep): LiquiditySweep {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_SmcZoneType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SmcZoneType): SmcZoneType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SmcZone_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SmcZone): SmcZone {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TradingSignalStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingSignalStatus): TradingSignalStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_TradingSignalType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingSignalType): TradingSignalType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TradingSignal_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradingSignal): TradingSignal {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketSentiment]): MarketSentiment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _ChartPatternDirection;
    accuracyPercentage: bigint;
    timeframe: string;
    patternName: string;
    description: string;
    detectionTimestamp: _Time;
    tradingPair: string;
}): {
    direction: ChartPatternDirection;
    accuracyPercentage: bigint;
    timeframe: string;
    patternName: string;
    description: string;
    detectionTimestamp: Time;
    tradingPair: string;
} {
    return {
        direction: from_candid_ChartPatternDirection_n27(_uploadFile, _downloadFile, value.direction),
        accuracyPercentage: value.accuracyPercentage,
        timeframe: value.timeframe,
        patternName: value.patternName,
        description: value.description,
        detectionTimestamp: value.detectionTimestamp,
        tradingPair: value.tradingPair
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priceLevel: number;
    volume: number;
    timestamp: _Time;
    sweepType: _LiquiditySweepType;
    tradingPair: string;
}): {
    priceLevel: number;
    volume: number;
    timestamp: Time;
    sweepType: LiquiditySweepType;
    tradingPair: string;
} {
    return {
        priceLevel: value.priceLevel,
        volume: value.volume,
        timestamp: value.timestamp,
        sweepType: from_candid_LiquiditySweepType_n32(_uploadFile, _downloadFile, value.sweepType),
        tradingPair: value.tradingPair
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priceLevel: number;
    timeframe: string;
    strength: bigint;
    zoneType: _SmcZoneType;
    timestamp: _Time;
    tradingPair: string;
}): {
    priceLevel: number;
    timeframe: string;
    strength: bigint;
    zoneType: SmcZoneType;
    timestamp: Time;
    tradingPair: string;
} {
    return {
        priceLevel: value.priceLevel,
        timeframe: value.timeframe,
        strength: value.strength,
        zoneType: from_candid_SmcZoneType_n38(_uploadFile, _downloadFile, value.zoneType),
        timestamp: value.timestamp,
        tradingPair: value.tradingPair
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TradingSignalStatus;
    takeProfit: number;
    stopLoss: number;
    timestamp: _Time;
    entryPrice: number;
    accuracyScore: bigint;
    tradingPair: string;
    strategyName: string;
    signalType: _TradingSignalType;
}): {
    status: TradingSignalStatus;
    takeProfit: number;
    stopLoss: number;
    timestamp: Time;
    entryPrice: number;
    accuracyScore: bigint;
    tradingPair: string;
    strategyName: string;
    signalType: TradingSignalType;
} {
    return {
        status: from_candid_TradingSignalStatus_n43(_uploadFile, _downloadFile, value.status),
        takeProfit: value.takeProfit,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        accuracyScore: value.accuracyScore,
        tradingPair: value.tradingPair,
        strategyName: value.strategyName,
        signalType: from_candid_TradingSignalType_n45(_uploadFile, _downloadFile, value.signalType)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
}): ChartPatternDirection {
    return "bullish" in value ? ChartPatternDirection.bullish : "bearish" in value ? ChartPatternDirection.bearish : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bsl: null;
} | {
    ssl: null;
}): LiquiditySweepType {
    return "bsl" in value ? LiquiditySweepType.bsl : "ssl" in value ? LiquiditySweepType.ssl : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bos: null;
} | {
    choch: null;
} | {
    fairValueGap: null;
} | {
    orderBlock: null;
}): SmcZoneType {
    return "bos" in value ? SmcZoneType.bos : "choch" in value ? SmcZoneType.choch : "fairValueGap" in value ? SmcZoneType.fairValueGap : "orderBlock" in value ? SmcZoneType.orderBlock : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
} | {
    pending: null;
}): TradingSignalStatus {
    return "closed" in value ? TradingSignalStatus.closed : "active" in value ? TradingSignalStatus.active : "pending" in value ? TradingSignalStatus.pending : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradingSignalType {
    return "buy" in value ? TradingSignalType.buy : "sell" in value ? TradingSignalType.sell : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChartPattern>): Array<ChartPattern> {
    return value.map((x)=>from_candid_ChartPattern_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LiquiditySweep>): Array<LiquiditySweep> {
    return value.map((x)=>from_candid_LiquiditySweep_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SmcZone>): Array<SmcZone> {
    return value.map((x)=>from_candid_SmcZone_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradingSignal>): Array<TradingSignal> {
    return value.map((x)=>from_candid_TradingSignal_n41(_uploadFile, _downloadFile, x));
}
function to_candid_ChartPatternDirection_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartPatternDirection): _ChartPatternDirection {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ChartPattern_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartPattern): _ChartPattern {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LiquiditySweepType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LiquiditySweepType): _LiquiditySweepType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_LiquiditySweep_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LiquiditySweep): _LiquiditySweep {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SmcZoneType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SmcZoneType): _SmcZoneType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SmcZone_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SmcZone): _SmcZone {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TradingSignalStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingSignalStatus): _TradingSignalStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_TradingSignalType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingSignalType): _TradingSignalType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TradingSignal_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingSignal): _TradingSignal {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priceLevel: number;
    timeframe: string;
    strength: bigint;
    zoneType: SmcZoneType;
    timestamp: Time;
    tradingPair: string;
}): {
    priceLevel: number;
    timeframe: string;
    strength: bigint;
    zoneType: _SmcZoneType;
    timestamp: _Time;
    tradingPair: string;
} {
    return {
        priceLevel: value.priceLevel,
        timeframe: value.timeframe,
        strength: value.strength,
        zoneType: to_candid_SmcZoneType_n11(_uploadFile, _downloadFile, value.zoneType),
        timestamp: value.timestamp,
        tradingPair: value.tradingPair
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TradingSignalStatus;
    takeProfit: number;
    stopLoss: number;
    timestamp: Time;
    entryPrice: number;
    accuracyScore: bigint;
    tradingPair: string;
    strategyName: string;
    signalType: TradingSignalType;
}): {
    status: _TradingSignalStatus;
    takeProfit: number;
    stopLoss: number;
    timestamp: _Time;
    entryPrice: number;
    accuracyScore: bigint;
    tradingPair: string;
    strategyName: string;
    signalType: _TradingSignalType;
} {
    return {
        status: to_candid_TradingSignalStatus_n15(_uploadFile, _downloadFile, value.status),
        takeProfit: value.takeProfit,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        accuracyScore: value.accuracyScore,
        tradingPair: value.tradingPair,
        strategyName: value.strategyName,
        signalType: to_candid_TradingSignalType_n17(_uploadFile, _downloadFile, value.signalType)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: ChartPatternDirection;
    accuracyPercentage: bigint;
    timeframe: string;
    patternName: string;
    description: string;
    detectionTimestamp: Time;
    tradingPair: string;
}): {
    direction: _ChartPatternDirection;
    accuracyPercentage: bigint;
    timeframe: string;
    patternName: string;
    description: string;
    detectionTimestamp: _Time;
    tradingPair: string;
} {
    return {
        direction: to_candid_ChartPatternDirection_n3(_uploadFile, _downloadFile, value.direction),
        accuracyPercentage: value.accuracyPercentage,
        timeframe: value.timeframe,
        patternName: value.patternName,
        description: value.description,
        detectionTimestamp: value.detectionTimestamp,
        tradingPair: value.tradingPair
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    priceLevel: number;
    volume: number;
    timestamp: Time;
    sweepType: LiquiditySweepType;
    tradingPair: string;
}): {
    priceLevel: number;
    volume: number;
    timestamp: _Time;
    sweepType: _LiquiditySweepType;
    tradingPair: string;
} {
    return {
        priceLevel: value.priceLevel,
        volume: value.volume,
        timestamp: value.timestamp,
        sweepType: to_candid_LiquiditySweepType_n7(_uploadFile, _downloadFile, value.sweepType),
        tradingPair: value.tradingPair
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SmcZoneType): {
    bos: null;
} | {
    choch: null;
} | {
    fairValueGap: null;
} | {
    orderBlock: null;
} {
    return value == SmcZoneType.bos ? {
        bos: null
    } : value == SmcZoneType.choch ? {
        choch: null
    } : value == SmcZoneType.fairValueGap ? {
        fairValueGap: null
    } : value == SmcZoneType.orderBlock ? {
        orderBlock: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingSignalStatus): {
    closed: null;
} | {
    active: null;
} | {
    pending: null;
} {
    return value == TradingSignalStatus.closed ? {
        closed: null
    } : value == TradingSignalStatus.active ? {
        active: null
    } : value == TradingSignalStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradingSignalType): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradingSignalType.buy ? {
        buy: null
    } : value == TradingSignalType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartPatternDirection): {
    bullish: null;
} | {
    bearish: null;
} {
    return value == ChartPatternDirection.bullish ? {
        bullish: null
    } : value == ChartPatternDirection.bearish ? {
        bearish: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LiquiditySweepType): {
    bsl: null;
} | {
    ssl: null;
} {
    return value == LiquiditySweepType.bsl ? {
        bsl: null
    } : value == LiquiditySweepType.ssl ? {
        ssl: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
